// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_exif_
DataFrame read_exif_(std::vector < std::string > files);
RcppExport SEXP exif_read_exif_(SEXP filesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type files(filesSEXP);
    __result = Rcpp::wrap(read_exif_(files));
    return __result;
END_RCPP
}
