# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title read EXIF data into R
#'@description \code{read_exif}
#'
#'@param filenames a vector of full filenames.
#'
#'@return A nested set of lists, containing
#'the metadata for each file. If only one file
#'is requested, the metadata will be at the "top level"
#'of the list, rather than unnecessarily nested; if
#'a file cannot be found or read correctly, the metadata
#'for that file will consist of the line "Could not read file".
#'
#'@export
read_exif <- function(filenames) {
    .Call('exif_read_exif', PACKAGE = 'exif', filenames)
}

